"""add users_app

Revision ID: 976bc2c8c6d9
Revises: 2f405ee59bf8
Create Date: 2024-08-02 18:22:39.718050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976bc2c8c6d9'
down_revision: Union[str, None] = '2f405ee59bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_app_email'), 'users_app', ['email'], unique=True)
    op.add_column('users', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users_app', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'owner_id')
    op.drop_index(op.f('ix_users_app_email'), table_name='users_app')
    op.drop_table('users_app')
    # ### end Alembic commands ###
